---
- name: Copy the jenkins dockerfile
  template: src=jenkins.Dockerfile.j2 dest=/data/jenkins.Dockerfile

- name: Create the nginx dir
  file:
    path: /data/nginx/config
    state: directory
    
- name: Copy the nginx dockerfile
  template: src=nginx.Dockerfile.j2 dest=/data/nginx/Dockerfile

- name: Copy the nginx config
  template: src=config/nginx.conf dest=/data/nginx/config/nginx.conf
  
- name: Copy the nginx config
  template: src=config/nginx.custom dest=/data/nginx/config/nginx.custom

- name: Build and start a new jenkins docker container
  docker_service:
    project_name: jenkins
    build: yes
    definition:
      version: '2'
      services:
        jenkins:
          image: jenkins/jenkins
          build:
            context: /data/
            dockerfile: jenkins.Dockerfile
          volumes:
            - "/data/jenkins_home:/var/jenkins_home"
          ports:
            - "8080:8080"
          restart: always
        nginx:
          build:
            context: /data/nginx
            dockerfile: Dockerfile
          ports:
            - "80:80"
            - "443:443"
          environment:
            - LAUNCH_ENV=custom
            - UPSTREAM_HOST=jenkins
            - UPSTREAM_PORT=8080
          volumes:
            - "/data/ssl:/etc/ssl"
          depends_on:
            - jenkins
          command: /bin/bash -c "envsubst '$$UPSTREAM_HOST $$UPSTREAM_PORT' < /tmp/nginx.custom > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    state: present
